//Script GUID:4b43950e-7c50-4837-b352-60ebbd58057e
//Used for tracking history

// --------------------------------------------------------------------------------------------------------------------
// Modules & References
// --------------------------------------------------------------------------------------------------------------------
// NGP Tagging Module
#DECLARE PrivacyAnnotationPath string = "/shares/PXSCosmos15.Prod/PXS.DeleteSignal.PROD/PrivacyAnnotation/PrivacyAnnotation.module";
MODULE @PrivacyAnnotationPath;

REFERENCE @"/shares/asimov.prod.data/Public/Resources/Latest/Device/Census/Microsoft.Telemetry.Device.Census.dll";
REFERENCE @"/shares/asimov.prod.data/Public/Resources/Latest/Device/Common/Microsoft.Telemetry.Common.Utilities.dll";

MODULE @"/shares/asimov.prod.data/PublicPartner/Processed/ACE/CSV/AppsCommonScriptUtilsModule.module";

//----------------------------------------------------------------------------------------------------------------------------------------------------

// Stream Parameters
#DECLARE oldStream string = @"/shares/asimov.prod.data/PublicPartner/Processed/ACE/Search/RelevanceScore/2022/08/AggregatedScore_2022_08_23.ss";
#DECLARE newStream string = @"/users/vijeetthomas/Search/RelevanceScore/2022/10/AggregatedScore_2022_10_30.ss";

oldData =   
    SELECT *
    FROM 
    (
        SSTREAM @oldStream
    );

oldData =  
    SELECT DISTINCT ProductId,
           Market,
           AggregateScore AS OldAggregateScore,
           RatingCountCleanedAG AS OldRatingCount
    FROM oldData
    WHERE Market IN ("US","GB","AU","CA")
          AND ProductId IN ("9P3CP9G025RM","9WZDNCRFHWQT","9P2HTZQ722V3","9N2F0P0166HF","9NBLGGH67WLK","9MWDP4QTXDXH","9WZDNCRD2WF1","9NWRS3JZK6FN","9NQTQNQVVDCK","9NBLGGH2JZSG");

newData =
    SELECT *
    FROM 
    (
        SSTREAM @newStream
    );

newData = 
    SELECT DISTINCT ProductId,
           Market,
           AggregateScore AS NewAggregateScore,
           RatingCountCleanedAG AS NewRatingCount
    FROM newData
    WHERE Market IN ("US","GB","AU","CA")
          AND ProductId IN ("9P3CP9G025RM","9WZDNCRFHWQT","9P2HTZQ722V3","9N2F0P0166HF","9NBLGGH67WLK","9MWDP4QTXDXH","9WZDNCRD2WF1","9NWRS3JZK6FN","9NQTQNQVVDCK","9NBLGGH2JZSG");

comparisonStream =
    SELECT o.ProductId,
           o.Market,
           o.OldAggregateScore,
           o.OldRatingCount,
           n.NewAggregateScore,
           n.NewRatingCount
    FROM oldData AS o
         LEFT JOIN
             newData AS n
         ON o.ProductId == n.ProductId
        AND o.Market  == n.Market;

OUTPUT comparisonStream
TO SSTREAM "/users/vijeetthomas/search/Comparison/StreamComparison.ss"
   WITH STREAMEXPIRY "7";
