input = 
    SELECT * 
    FROM(VALUES 
          ("{\"name\": \"alice\"}", 1),
          ("{\"name\": \"bob\"}", 2)
    ) AS Value(jsonString, id)
    ;

jsonParseSet = 
    SELECT 
        JSON.Parse<string>(jsonString, "name") AS userName, 
        id AS userId
    FROM input
    ;

scopeJsonParseSet = 
    SELECT 
        ScopeJson.Parse<string>(jsonString, "name") AS userName, 
        id AS userId
    FROM input
    ;